volumes:
  pg_data:

services:
  pgsql:
    restart: unless-stopped
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: notsecurepassword
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser -d pgdb" ]
      interval: 5s
      timeout: 3s
      retries: 10

  valkey:
    restart: unless-stopped
    image: valkey/valkey:8-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  worker:
    depends_on: [ pgsql, valkey ]
    restart: unless-stopped
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://pguser:notsecurepassword@pgsql:5432/pgdb
      REDIS_URL: redis://valkey:6379
    healthcheck:
      test: [ "CMD", "node", "dist/healthcheck.js" ]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    depends_on:
      pgsql:
        condition: service_healthy
      valkey:
        condition: service_healthy
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://pguser:notsecurepassword@pgsql:5432/pgdb
      REDIS_URL: redis://valkey:6379
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/v1/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      